<div class="laminas-toolbar-entry">
    <div class="laminas-toolbar-preview">
        <img src="data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wHAw8kLbbW/+QAAAHwSURBVDjLnVTPq1JBFD7nznivgbcoJQliMnGZK0HbRNhKgsCdC2lh7dy58A/I/gHBv+QhBO8tXnvJlbUIxHIEKXKjoGnjzLR518Z7Nd+732p+fnO+850zCAZms9lTIcQFALhwGgoR3yWTyfeIqL1FBADgnCNjTDcajY9CCAYA4hqESCldt9vtZ5zzBWPsH+EV6ZfFYvFYKUXgmkBE7bouSaVSEW+N7uJXKhGLxW4Zh8GyrACJ1hqUUtoMxoRJuLcxnU7/dDqd74SQPfmFQuFhuVy+I6U8HLU3GA6HPwHgvjeXUl4ul8uhbdtvtN7lXK5Wq1fxePzCJMlkMhggHI1GvwAgASGQTqcxILlerw8A4F4IvtsHJQ8Ggx+m5BsAs9lsMMIrcjRdjkQiYORvZ56U8rTLftcmk8mm1Wp9tSxLmI8Ui8VH1Wo1sd1u/+9yv9/fcxkRLwkh35RSb43zkhDyUghxbpLkcrmgZEqpv0NeAIC/uInW+pxSejShu51KpfIJAO6GMMU9KLnX64Wuw3w+H5S82WyUr/HBtu3AZSklCCE0It6sl8fj8e9ms/mZUrpnZ6lUStVqtQfHevlo2TDGet1ulwshXpufTTQaLc/n87OTpjiO47fuuRCBfxbX6/WZ4zjH28aI6ENYlznnT7zJX1iYwsqME23RAAAAAElFTkSuQmCCSUVORK5CYII=" alt="Memory Peak">
        <span class="laminas-toolbar-info">
            <?php echo $this->LaminasDeveloperToolsMemory($this->collector->getMemory()); ?>
        </span>
    </div>
    <div class="laminas-toolbar-detail<?php echo ($this->collector->hasEventMemory()) ? ' laminas-toolbar-detail-overflow' : ' laminas-toolbar-detail-redundant' ;?>">
        <?php if ($this->collector->hasEventMemory()): ?>
            <?php foreach ($this->collector->getApplicationEventMemory() as $key => $value): ?>
                <span class="laminas-toolbar-info">
                <span class="laminas-detail-label"><?php printf('%d. %s', $key + 1, $value['name']); ?></span>
                <span class="laminas-detail-value laminas-detail-value-right"><?php echo $this->LaminasDeveloperToolsMemory($value['difference']); ?></span>
                <p class="laminas-detail-context"><?php printf('%s - Line: %d', $value['file'], $value['line']); ?></p>
                </span>
            <?php endforeach; ?>
        <?php endif; ?>
        <span class="laminas-toolbar-info laminas-toolbar-info-redundant<?php echo ($this->collector->hasEventMemory()) ? ' laminas-toolbar-topspacing' : '' ;?>">
            <span class="laminas-detail-label">Memory Peak</span>
            <span class="laminas-detail-value laminas-detail-value-right">
                <?php echo $this->LaminasDeveloperToolsMemory($this->collector->getMemory()); ?>
            </span>
        </span>
    </div>
</div>