<!-- START Laminas Developer Toolbar Style -->
<style type="text/css" media="all">
<?php include __DIR__ . '/toolbar.css'; ?>

<?php if ($this->position === 'top') : ?>
#laminas-developer-toolbar {
    top: 0;
    bottom: auto;
    border-top: 0;
    border-bottom: 1px solid #111;
}

.laminas-toolbar-detail {
    top: 39px;
    bottom: auto;
}

.laminas-toolbar-detail:before,
.laminas-toolbar-detail:after {
    left: 14px;
    top: -10px;
    bottom: auto;
    border-top: 0;
    border-bottom: 10px solid #68B604;
}
<?php endif; ?>
</style>
<!-- END Laminas Developer Toolbar Style -->
